'use client';

import { useEffect, useMemo, useRef, useState } from 'react';

export type FacialStudent = { id: string; full_name: string; admission_number: string; };
type MatchResult = { faceId:string; studentId:string|null; studentName:string|null; confidence:number|null; status:'strong'|'review'|'unknown'; };
type Props = { className:string; classId:string; students:FacialStudent[]; onApplyPresent:(studentIds:string[])=>void; };

export default function FacialAttendancePanel({className,classId,students,onApplyPresent}:Props){
 const cameraInput=useRef<HTMLInputElement|null>(null); const uploadInput=useRef<HTMLInputElement|null>(null);
 const [photos,setPhotos]=useState<File[]>([]); const [results,setResults]=useState<MatchResult[]>([]); const [processing,setProcessing]=useState(false); const [message,setMessage]=useState('');
 const previews=useMemo(()=>photos.map(file=>({file,url:URL.createObjectURL(file)})),[photos]);
 useEffect(()=>()=>previews.forEach(x=>URL.revokeObjectURL(x.url)),[previews]);
 function addPhotos(files:FileList|null){if(!files)return; setPhotos(p=>[...p,...Array.from(files).filter(f=>f.type.startsWith('image/'))]); setResults([]);}
 async function processPhotos(){ if(!classId){setMessage('Select one specific class before using facial attendance.');return;} if(!photos.length){setMessage('Take or upload at least one classroom photo.');return;} setProcessing(true);setMessage(''); try{const form=new FormData();form.append('classId',classId);photos.forEach(p=>form.append('photos',p)); const response=await fetch('/api/facial-attendance/process',{method:'POST',body:form});const data=await response.json();if(!response.ok)throw new Error(data?.error||'Could not process classroom photos.');const matches:MatchResult[]=data.matches??[];setResults(matches);const ids=matches.filter(m=>m.status==='strong'&&m.studentId).map(m=>m.studentId as string);onApplyPresent([...new Set(ids)]);setMessage(data.message||`${ids.length} students proposed as present.`);}catch(e:any){setMessage(e?.message||'Processing failed.');}finally{setProcessing(false);}}
 function confirm(faceId:string,studentId:string){setResults(p=>p.map(r=>r.faceId===faceId?{...r,status:'strong'}:r));onApplyPresent([studentId]);}
 function reject(faceId:string){setResults(p=>p.map(r=>r.faceId===faceId?{...r,studentId:null,studentName:null,status:'unknown'}:r));}
 return <section className="rounded-3xl border border-blue-200 bg-white p-4 shadow-sm sm:p-6">
  <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="inline-flex items-center gap-2 rounded-full bg-blue-50 px-3 py-1.5 text-xs font-black text-blue-700"><i className="fa-solid fa-camera"/> Facial Attendance</div><h2 className="mt-3 text-xl font-black text-slate-900">{className||'Select a Class'}</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-500">Take photos now or upload classroom photos taken earlier when there was no internet.</p></div><div className="rounded-2xl bg-amber-50 px-4 py-3 text-xs font-semibold text-amber-800">Not detected does not automatically mean absent.</div></div>
  {!classId&&<div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm font-bold text-amber-800">Choose one specific class. Facial attendance is disabled for All Classes.</div>}
  <div className="mt-6 grid gap-3 sm:grid-cols-2"><button type="button" disabled={!classId} onClick={()=>cameraInput.current?.click()} className="rounded-2xl bg-blue-600 px-5 py-4 font-black text-white disabled:opacity-40"><i className="fa-solid fa-camera mr-2"/>Take Photos Now</button><button type="button" disabled={!classId} onClick={()=>uploadInput.current?.click()} className="rounded-2xl border border-slate-300 bg-white px-5 py-4 font-black text-slate-700 disabled:opacity-40"><i className="fa-solid fa-cloud-arrow-up mr-2"/>Upload Photos</button><input ref={cameraInput} type="file" accept="image/*" capture="environment" className="hidden" onChange={e=>addPhotos(e.target.files)}/><input ref={uploadInput} type="file" accept="image/*" multiple className="hidden" onChange={e=>addPhotos(e.target.files)}/></div>
  {!!photos.length&&<div className="mt-6"><div className="flex items-center justify-between"><h3 className="font-black">Classroom Photos ({photos.length})</h3><button type="button" onClick={()=>{setPhotos([]);setResults([])}} className="text-xs font-black text-red-600">Clear All</button></div><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{previews.map((x,i)=><div key={i} className="overflow-hidden rounded-2xl border"><img src={x.url} alt={`Classroom photo ${i+1}`} className="h-28 w-full object-cover"/><div className="flex justify-between p-2 text-xs font-bold">Photo {i+1}<button type="button" onClick={()=>setPhotos(p=>p.filter((_,j)=>j!==i))} className="text-red-600"><i className="fa-solid fa-trash"/></button></div></div>)}</div><button type="button" onClick={processPhotos} disabled={processing} className="mt-5 rounded-2xl bg-slate-950 px-6 py-4 text-sm font-black text-white disabled:opacity-60">{processing?'Processing Faces...':'Process Attendance'}</button></div>}
  {message&&<div className="mt-5 rounded-2xl bg-blue-50 px-4 py-3 text-sm font-semibold text-blue-800">{message}</div>}
  {!!results.length&&<div className="mt-6 space-y-3">{results.map(r=><div key={r.faceId} className="rounded-2xl border p-4"><p className="font-black">{r.studentName||'Unknown Face'}</p><p className="mt-1 text-xs text-slate-500">{r.status==='strong'?'Strong match — proposed Present':r.status==='review'?'Low-confidence match — confirm below':'No reliable student match'}</p>{r.status==='review'&&r.studentId&&<div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={()=>confirm(r.faceId,r.studentId!)} className="rounded-xl bg-emerald-600 px-4 py-2 text-xs font-black text-white">Same Person</button><button type="button" onClick={()=>reject(r.faceId)} className="rounded-xl bg-red-600 px-4 py-2 text-xs font-black text-white">Different Person</button><button type="button" className="rounded-xl border px-4 py-2 text-xs font-black">Not Sure</button></div>}</div>)}</div>}
 </section>;
}
