'use client';
import {useEffect,useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import {createClient} from '@/lib/supabase/client';
import * as XLSX from 'xlsx';
type P={id:string;school_id:string;full_name:string;role:string;is_active:boolean|null};type S={id:string;admission_number:string|null;full_name:string;gender:string|null;resident:string|null;guardian_phone:string|null};type Y={id:string;name:string;start_date:string;is_current:boolean|null};type E={student_id:string;academic_year_id:string;class_id:string;programme_id:string|null;status:string|null};type C={id:string;name:string;level:string|null;programme_id:string|null};type G={id:string;name:string;code:string|null};type H={id:string;name:string};type R={id:string;house_id:string;room_number:string;capacity:number;is_active:boolean};type A={student_id:string;academic_year_id:string;house_id:string;room_id:string;status:string};type I={student_id:string;incident_at:string;severity:string;status:string};type O={student_id:string;checkout_at:string;expected_return_at:string|null;returned_at:string|null;status:string};
const sb=createClient(),input='h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm font-semibold outline-none focus:border-slate-400 focus:bg-white focus:ring-4 focus:ring-slate-100';
export default function Reports(){const router=useRouter();const[p,setP]=useState<P|null>(null),[ss,setSs]=useState<S[]>([]),[ys,setYs]=useState<Y[]>([]),[en,setEn]=useState<E[]>([]),[cl,setCl]=useState<C[]>([]),[pr,setPr]=useState<G[]>([]),[hs,setHs]=useState<H[]>([]),[rs,setRs]=useState<R[]>([]),[al,setAl]=useState<A[]>([]),[ins,setIns]=useState<I[]>([]),[outs,setOuts]=useState<O[]>([]),[year,setYear]=useState(''),[programme,setProgramme]=useState('All'),[residence,setResidence]=useState('All'),[loading,setLoading]=useState(true),[msg,setMsg]=useState('');
async function load(school:string){const q=await Promise.all([sb.from('students').select('id,admission_number,full_name,gender,resident,guardian_phone').eq('school_id',school).eq('status','active').order('full_name'),sb.from('academic_years').select('id,name,start_date,is_current').eq('school_id',school).order('start_date',{ascending:false}),sb.from('classes').select('id,name,level,programme_id').eq('school_id',school),sb.from('programmes').select('id,name,code').eq('school_id',school).order('name'),sb.from('residential_houses').select('id,name').eq('school_id',school),sb.from('residential_rooms').select('id,house_id,room_number,capacity,is_active').eq('school_id',school),sb.from('student_incidents').select('student_id,incident_at,severity,status').eq('school_id',school),sb.from('student_checkouts').select('student_id,checkout_at,expected_return_at,returned_at,status').eq('school_id',school)]);const er=q.find(x=>x.error)?.error;if(er)throw new Error(er.message);setSs((q[0].data||[])as S[]);setYs((q[1].data||[])as Y[]);setCl((q[2].data||[])as C[]);setPr((q[3].data||[])as G[]);setHs((q[4].data||[])as H[]);setRs((q[5].data||[])as R[]);setIns((q[6].data||[])as I[]);setOuts((q[7].data||[])as O[]);const cy=(q[1].data||[]).find((x:any)=>x.is_current)||(q[1].data||[])[0];if(cy){setYear(cy.id);await loadYear(school,cy.id,(q[0].data||[]).map((x:any)=>x.id))}}
async function loadYear(school:string,y:string,ids=ss.map(s=>s.id)){if(!ids.length){setEn([]);setAl([]);return}const[a,b]=await Promise.all([sb.from('enrollments').select('student_id,academic_year_id,class_id,programme_id,status').eq('academic_year_id',y).eq('status','active').in('student_id',ids),sb.from('boarding_allocations').select('student_id,academic_year_id,house_id,room_id,status').eq('school_id',school).eq('academic_year_id',y).eq('status','Active').in('student_id',ids)]);if(a.error||b.error)throw new Error(a.error?.message||b.error?.message);setEn((a.data||[])as E[]);setAl((b.data||[])as A[])}
useEffect(()=>{(async()=>{const{data:{user}}=await sb.auth.getUser();if(!user){router.replace('/login');return}const{data:u}=await sb.from('users').select('id,school_id,full_name,role,is_active').eq('id',user.id).maybeSingle();if(!u||u.is_active===false||!['housemaster','admin'].includes(u.role)){router.replace('/login');return}setP(u as P);try{await load(u.school_id)}catch(e){setMsg(e instanceof Error?e.message:'Unable to load reports.')}finally{setLoading(false)}})()},[router]);
async function changeYear(y:string){if(!p)return;setYear(y);setLoading(true);try{await loadYear(p.school_id,y)}catch(e){setMsg(e instanceof Error?e.message:'Unable to load year.')}finally{setLoading(false)}}
const cm=useMemo(()=>new Map(cl.map(x=>[x.id,x])),[cl]),pm=useMemo(()=>new Map(pr.map(x=>[x.id,x])),[pr]),hm=useMemo(()=>new Map(hs.map(x=>[x.id,x])),[hs]),rm=useMemo(()=>new Map(rs.map(x=>[x.id,x])),[rs]),em=useMemo(()=>new Map(en.map(x=>[x.student_id,x])),[en]),am=useMemo(()=>new Map(al.map(x=>[x.student_id,x])),[al]),awayIds=new Set(outs.filter(x=>x.status==='Checked Out').map(x=>x.student_id));
function acad(s:S){const e=em.get(s.id),c=e?cm.get(e.class_id):undefined,p=e?pm.get(e.programme_id||c?.programme_id||''):undefined;return{e,c,p}}
const rows=ss.filter(s=>{const a=acad(s);return(residence==='All'||(residence==='Boarder'?s.resident==='Boarding':s.resident===residence))&&(programme==='All'||a.p?.id===programme)}),boarders=rows.filter(s=>s.resident==='Boarding'),day=rows.filter(s=>s.resident==='Day'),away=rows.filter(s=>awayIds.has(s.id)),openInc=ins.filter(i=>i.status==='Open'||i.status==='Under Review').filter(i=>rows.some(s=>s.id===i.student_id)),critical=ins.filter(i=>i.severity==='Critical'&&i.status!=='Resolved'&&i.status!=='Closed').filter(i=>rows.some(s=>s.id===i.student_id)),capacity=rs.filter(r=>r.is_active).reduce((n,r)=>n+r.capacity,0),occupied=al.filter(a=>rows.some(s=>s.id===a.student_id)).length,overdue=outs.filter(o=>o.status==='Checked Out'&&o.expected_return_at&&new Date(o.expected_return_at)<new Date()&&rows.some(s=>s.id===o.student_id)).length;
function exportXlsx(){const data=rows.map(s=>{const a=acad(s),ba=am.get(s.id),h=ba?hm.get(ba.house_id):undefined,r=ba?rm.get(ba.room_id):undefined;return{'Admission No.':s.admission_number||'',Student:s.full_name,Gender:s.gender||'',Residence:s.resident==='Boarding'?'Boarder':s.resident||'',Programme:a.p?.name||'',Form:a.c?.level||'',Class:a.c?.name||'',House:h?.name||'',Room:r?.room_number||'','Campus Status':awayIds.has(s.id)?'Away':'On Campus','Guardian Phone':s.guardian_phone||''}});const wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(data);XLSX.utils.book_append_sheet(wb,ws,'Residential Report');XLSX.writeFile(wb,`BTI-Residential-Report-${ys.find(y=>y.id===year)?.name||'Year'}.xlsx`)}
if(loading&&!p)return <main className="min-h-screen bg-slate-50 p-6"><div className="mx-auto h-40 max-w-7xl animate-pulse rounded-3xl bg-slate-900"/></main>;
return <main className="min-h-screen bg-slate-50 px-4 py-5 sm:px-6 lg:px-8"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"/><div className="mx-auto max-w-7xl space-y-6"><header className="rounded-3xl bg-gradient-to-br from-slate-950 via-slate-900 to-slate-800 p-6 text-white shadow-xl sm:p-8"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><span className="rounded-full bg-white/10 px-3 py-1.5 text-xs font-bold"><i className="fa-solid fa-chart-column mr-2"/>Residential Intelligence</span><h1 className="mt-4 text-2xl font-black sm:text-3xl">Housemaster Reports</h1><p className="mt-2 text-sm text-slate-300">Residential population, occupancy, movement and welfare information in one operational report.</p></div><button onClick={exportXlsx} className="rounded-xl bg-white px-4 py-3 text-sm font-extrabold text-slate-900"><i className="fa-solid fa-file-excel mr-2"/>Export Excel</button></div></header>{msg&&<div className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{msg}</div>}
<section className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-3"><select className={input} value={year} onChange={e=>changeYear(e.target.value)}>{ys.map(y=><option key={y.id} value={y.id}>{y.name}</option>)}</select><select className={input} value={residence} onChange={e=>setResidence(e.target.value)}><option>All</option><option value="Boarder">Boarders</option><option>Day</option></select><select className={input} value={programme} onChange={e=>setProgramme(e.target.value)}><option value="All">All Programmes</option>{pr.map(x=><option key={x.id} value={x.id}>{x.code||x.name} — {x.name}</option>)}</select></div></section>
<section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Stat i="fa-users" l="Students" n={rows.length}/><Stat i="fa-bed" l="Boarders" n={boarders.length}/><Stat i="fa-house" l="Day Students" n={day.length}/><Stat i="fa-person-walking-arrow-right" l="Currently Away" n={away.length}/><Stat i="fa-door-open" l="Room Capacity" n={capacity}/><Stat i="fa-user-check" l="Allocated Beds" n={occupied}/><Stat i="fa-clock" l="Overdue Returns" n={overdue}/><Stat i="fa-triangle-exclamation" l="Open Incidents" n={openInc.length}/></section>
{critical.length>0&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700"><i className="fa-solid fa-bell mr-2"/>Critical unresolved incidents: {critical.length}</div>}
<section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 p-5"><h2 className="font-black text-slate-900">Residential Student Register</h2><p className="mt-1 text-xs text-slate-500">{rows.length} record(s) under the selected filters</p></div><div className="overflow-x-auto"><table className="min-w-full text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr>{['Student','Residence','Programme / Class','Accommodation','Campus Status','Guardian'].map(x=><th key={x} className="px-4 py-3 font-extrabold">{x}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map(s=>{const a=acad(s),ba=am.get(s.id),h=ba?hm.get(ba.house_id):undefined,r=ba?rm.get(ba.room_id):undefined;return <tr key={s.id} className="hover:bg-slate-50"><td className="px-4 py-3"><b className="text-slate-900">{s.full_name}</b><div className="mt-1 text-slate-500">{s.admission_number||'—'}</div></td><td className="px-4 py-3">{s.resident==='Boarding'?'Boarder':s.resident||'—'}</td><td className="px-4 py-3">{a.p?.code||a.p?.name||'—'}<div className="mt-1 text-slate-500">{a.c?.level||'—'} · {a.c?.name||'—'}</div></td><td className="px-4 py-3">{h?.name||'—'}<div className="mt-1 text-slate-500">{r?.room_number||''}</div></td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 font-bold ${awayIds.has(s.id)?'bg-amber-50 text-amber-700':'bg-emerald-50 text-emerald-700'}`}>{awayIds.has(s.id)?'Away':'On Campus'}</span></td><td className="px-4 py-3">{s.guardian_phone||'—'}</td></tr>})}</tbody></table></div></section></div></main>}
function Stat({i,l,n}:{i:string;l:string;n:number}){return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-100"><i className={`fa-solid ${i}`}/></span><div><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{l}</p><p className="text-xl font-black text-slate-900">{n}</p></div></div></div>}
