'use client';
import {useEffect,useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import {createClient} from '@/lib/supabase/client';
import * as XLSX from 'xlsx';
type P={id:string;school_id:string;full_name:string;role:string;is_active:boolean|null};type S={id:string;admission_number:string|null;full_name:string;gender:string|null;guardian_phone:string|null};type Y={id:string;name:string;start_date:string;is_current:boolean|null};type E={student_id:string;class_id:string;programme_id:string|null};type C={id:string;name:string;level:string|null;programme_id:string|null};type G={id:string;name:string;code:string|null};type H={id:string;name:string};type R={id:string;house_id:string;room_number:string;capacity:number;is_active:boolean};type A={student_id:string;house_id:string;room_id:string|null;room_number:string;bed_space:string|null};type I={student_id:string;severity:string;status:string};type O={student_id:string;expected_return_at:string|null;status:string};type X={student_id:string;expected_return_at:string;status:string};
const sb=createClient(),input='h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm font-semibold outline-none transition focus:bg-white focus:ring-4 focus:ring-slate-100';
export default function Reports(){const router=useRouter();const[p,setP]=useState<P|null>(null),[ss,setSs]=useState<S[]>([]),[ys,setYs]=useState<Y[]>([]),[en,setEn]=useState<E[]>([]),[cl,setCl]=useState<C[]>([]),[pr,setPr]=useState<G[]>([]),[hs,setHs]=useState<H[]>([]),[rs,setRs]=useState<R[]>([]),[al,setAl]=useState<A[]>([]),[ins,setIns]=useState<I[]>([]),[outs,setOuts]=useState<O[]>([]),[exiats,setExiats]=useState<X[]>([]),[year,setYear]=useState(''),[programme,setProgramme]=useState('All'),[loading,setLoading]=useState(true),[msg,setMsg]=useState('');
async function load(school:string){const q=await Promise.all([sb.from('students').select('id,admission_number,full_name,gender,guardian_phone').eq('school_id',school).eq('resident','Boarding').eq('status','active').order('full_name'),sb.from('academic_years').select('id,name,start_date,is_current').eq('school_id',school).order('start_date',{ascending:false}),sb.from('classes').select('id,name,level,programme_id').eq('school_id',school),sb.from('programmes').select('id,name,code').eq('school_id',school).order('name'),sb.from('residential_houses').select('id,name').eq('school_id',school),sb.from('residential_rooms').select('id,house_id,room_number,capacity,is_active').eq('school_id',school),sb.from('student_incidents').select('student_id,severity,status').eq('school_id',school),sb.from('student_checkouts').select('student_id,expected_return_at,status').eq('school_id',school),sb.from('student_exiats').select('student_id,expected_return_at,status').eq('school_id',school)]);const er=q.find(x=>x.error)?.error;if(er)throw new Error(er.message);const b=(q[0].data||[])as S[],ids=new Set(b.map(x=>x.id));setSs(b);setYs((q[1].data||[])as Y[]);setCl((q[2].data||[])as C[]);setPr((q[3].data||[])as G[]);setHs((q[4].data||[])as H[]);setRs((q[5].data||[])as R[]);setIns(((q[6].data||[])as I[]).filter(x=>ids.has(x.student_id)));setOuts(((q[7].data||[])as O[]).filter(x=>ids.has(x.student_id)));setExiats(((q[8].data||[])as X[]).filter(x=>ids.has(x.student_id)));const cy=(q[1].data||[]).find((x:any)=>x.is_current)||(q[1].data||[])[0];if(cy){setYear(cy.id);await loadYear(school,cy.id,b.map(x=>x.id))}}
async function loadYear(school:string,y:string,ids=ss.map(s=>s.id)){if(!ids.length){setEn([]);setAl([]);return}const[a,b]=await Promise.all([sb.from('enrollments').select('student_id,class_id,programme_id').eq('academic_year_id',y).eq('status','active').in('student_id',ids),sb.from('boarding_allocations').select('student_id,house_id,room_id,room_number,bed_space').eq('school_id',school).eq('academic_year_id',y).eq('status','Active').in('student_id',ids)]);if(a.error||b.error)throw new Error(a.error?.message||b.error?.message);setEn((a.data||[])as E[]);setAl((b.data||[])as A[])}
useEffect(()=>{(async()=>{const{data:{user}}=await sb.auth.getUser();if(!user){router.replace('/login');return}const{data:u}=await sb.from('users').select('id,school_id,full_name,role,is_active').eq('id',user.id).maybeSingle();if(!u||u.is_active===false||!['housemaster','admin'].includes(u.role)){router.replace('/login');return}setP(u as P);try{await load(u.school_id)}catch(e){setMsg(e instanceof Error?e.message:'Unable to load reports.')}finally{setLoading(false)}})()},[router]);
async function changeYear(y:string){if(!p)return;setYear(y);try{await loadYear(p.school_id,y)}catch(e){setMsg(e instanceof Error?e.message:'Unable to load year.')}}
const cm=useMemo(()=>new Map(cl.map(x=>[x.id,x])),[cl]),pm=useMemo(()=>new Map(pr.map(x=>[x.id,x])),[pr]),hm=useMemo(()=>new Map(hs.map(x=>[x.id,x])),[hs]),rm=useMemo(()=>new Map(rs.map(x=>[x.id,x])),[rs]),em=useMemo(()=>new Map(en.map(x=>[x.student_id,x])),[en]),am=useMemo(()=>new Map(al.map(x=>[x.student_id,x])),[al]);
function acad(s:S){const e=em.get(s.id),c=e?cm.get(e.class_id):undefined,g=e?pm.get(e.programme_id||c?.programme_id||''):undefined;return{c,g}}
const rows=ss.filter(s=>programme==='All'||acad(s).g?.id===programme),ids=new Set(rows.map(x=>x.id)),checkoutIds=new Set(outs.filter(x=>x.status==='Checked Out').map(x=>x.student_id)),exiatIds=new Set(exiats.filter(x=>x.status==='Out').map(x=>x.student_id)),awayIds=new Set([...checkoutIds,...exiatIds]),allocated=rows.filter(s=>am.has(s.id)),needs=rows.filter(s=>!am.has(s.id)),capacity=rs.filter(r=>r.is_active).reduce((n,r)=>n+r.capacity,0),openInc=ins.filter(i=>ids.has(i.student_id)&&(i.status==='Open'||i.status==='Under Review')),critical=ins.filter(i=>ids.has(i.student_id)&&i.severity==='Critical'&&!['Resolved','Closed'].includes(i.status)),overdueCheckout=outs.filter(o=>ids.has(o.student_id)&&o.status==='Checked Out'&&o.expected_return_at&&new Date(o.expected_return_at)<new Date()).length,overdueExiat=exiats.filter(x=>ids.has(x.student_id)&&x.status==='Out'&&new Date(x.expected_return_at)<new Date()).length;
function exportXlsx(){const data=rows.map(s=>{const a=acad(s),ba=am.get(s.id),h=ba?hm.get(ba.house_id):undefined,r=ba?rm.get(ba.room_id||''):undefined;return{'Admission No.':s.admission_number||'',Boarder:s.full_name,Gender:s.gender||'',Programme:a.g?.name||'',Form:a.c?.level||'',Class:a.c?.name||'',House:h?.name||'',Room:ba?.room_number||r?.room_number||'','Bed Space':ba?.bed_space||'','Campus Status':awayIds.has(s.id)?'Away':'On Campus','Movement Type':exiatIds.has(s.id)?'Exiat':checkoutIds.has(s.id)?'Checkout/Vacation':'','Guardian Phone':s.guardian_phone||''}});const wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(data);XLSX.utils.book_append_sheet(wb,ws,'Boarder Report');XLSX.writeFile(wb,`BTI-Boarder-Report-${ys.find(y=>y.id===year)?.name||'Year'}.xlsx`)}
if(loading&&!p)return <main className="min-h-screen bg-slate-50 p-6"><div className="h-40 animate-pulse rounded-3xl bg-slate-900"/></main>;
return <main className="min-h-screen bg-slate-50 px-4 py-5 sm:px-6 lg:px-8"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"/><div className="mx-auto max-w-7xl space-y-6"><header className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-slate-950 via-slate-900 to-slate-800 p-6 text-white shadow-xl sm:p-8"><div className="absolute -right-20 -top-20 h-56 w-56 animate-pulse rounded-full bg-emerald-400/10"/><div className="relative flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><span className="rounded-full bg-white/10 px-3 py-1.5 text-xs font-black"><i className="fa-solid fa-chart-column mr-2"/>Boarder Intelligence</span><h1 className="mt-4 text-3xl font-black">Housemaster Reports</h1><p className="mt-2 text-sm text-slate-300">Accommodation, movement, Exiat and welfare reporting for active Boarders only.</p></div><button onClick={exportXlsx} className="rounded-xl bg-white px-4 py-3 text-sm font-black text-slate-900 transition hover:-translate-y-0.5"><i className="fa-solid fa-file-excel mr-2"/>Export Excel</button></div></header>{msg&&<div className="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{msg}</div>}
<section className="rounded-3xl border bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-2"><select className={input} value={year} onChange={e=>changeYear(e.target.value)}>{ys.map(y=><option key={y.id} value={y.id}>{y.name}</option>)}</select><select className={input} value={programme} onChange={e=>setProgramme(e.target.value)}><option value="All">All Programmes</option>{pr.map(x=><option key={x.id} value={x.id}>{x.code||x.name} — {x.name}</option>)}</select></div></section>
<section className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Stat i="fa-users" l="Active Boarders" n={rows.length}/><Stat i="fa-bed" l="Allocated" n={allocated.length}/><Stat i="fa-user-clock" l="Needs Room" n={needs.length}/><Stat i="fa-house-circle-check" l="On Campus" n={Math.max(0,rows.length-awayIds.size)}/><Stat i="fa-person-walking-arrow-right" l="Checkout / Vacation" n={[...checkoutIds].filter(x=>ids.has(x)).length}/><Stat i="fa-person-walking-arrow-right" l="On Exiat" n={[...exiatIds].filter(x=>ids.has(x)).length}/><Stat i="fa-triangle-exclamation" l="Open Incidents" n={openInc.length}/><Stat i="fa-clock" l="Overdue Returns" n={overdueCheckout+overdueExiat}/></section>
<div className="grid gap-3 md:grid-cols-3"><Info i="fa-door-open" l="Active Room Capacity" n={capacity}/><Info i="fa-bed" l="Available Capacity" n={Math.max(0,capacity-allocated.length)}/><Info i="fa-bell" l="Critical Unresolved" n={critical.length}/></div>
<section className="overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-black">Boarder Register</h2><p className="mt-1 text-xs text-slate-500">{rows.length} Boarder(s) under the selected filters</p></div><div className="overflow-x-auto"><table className="min-w-full text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr>{['Boarder','Programme / Class','Accommodation','Campus Status','Movement','Guardian'].map(x=><th key={x} className="px-4 py-3 font-black">{x}</th>)}</tr></thead><tbody className="divide-y">{rows.map(s=>{const a=acad(s),ba=am.get(s.id),h=ba?hm.get(ba.house_id):undefined,r=ba?rm.get(ba.room_id||''):undefined;return <tr key={s.id} className="transition hover:bg-slate-50"><td className="px-4 py-3"><b>{s.full_name}</b><div className="mt-1 text-slate-500">{s.admission_number||'—'}</div></td><td className="px-4 py-3">{a.g?.code||a.g?.name||'—'}<div className="mt-1 text-slate-500">{a.c?.level||'—'} · {a.c?.name||'—'}</div></td><td className="px-4 py-3">{h?.name||'Needs Allocation'}<div className="mt-1 text-slate-500">{ba?.room_number||r?.room_number||'—'} {ba?.bed_space?`· ${ba.bed_space}`:''}</div></td><td className="px-4 py-3"><B t={awayIds.has(s.id)?'Away':'On Campus'}/></td><td className="px-4 py-3">{exiatIds.has(s.id)?'Exiat':checkoutIds.has(s.id)?'Checkout / Vacation':'—'}</td><td className="px-4 py-3">{s.guardian_phone||'—'}</td></tr>})}</tbody></table></div></section></div></main>}
function Stat({i,l,n}:{i:string;l:string;n:number}){return <div className="group rounded-2xl border bg-white p-4 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><i className={`fa-solid ${i} text-slate-400 transition-transform group-hover:scale-125`}/><p className="mt-2 text-2xl font-black">{n}</p><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{l}</p></div>}function Info({i,l,n}:{i:string;l:string;n:number}){return <div className="rounded-2xl border bg-white p-4"><i className={`fa-solid ${i} mr-3 text-slate-400`}/><b>{n}</b><span className="ml-2 text-xs text-slate-500">{l}</span></div>}function B({t}:{t:string}){return <span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold">{t}</span>}
