import Link from 'next/link';
import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';

const groups=[
  {title:'School & Accounts',description:'Manage staff records, portal access and the school administration structure.',icon:'fa-school',links:[['Staff records','/staff','fa-users'],['Portal accounts','/portal-accounts','fa-user-shield'],['Programmes','/programmes','fa-layer-group'],['Classes','/classes','fa-school-flag']]},
  {title:'Academic Configuration',description:'Control the academic structure used by attendance, assessment and reports.',icon:'fa-graduation-cap',links:[['Academic years','/academic-years','fa-calendar-days'],['Semesters','/terms','fa-calendar-week'],['Subjects','/subjects','fa-book-open'],['Teacher assignments','/teacher-assignments','fa-chalkboard-user'],['Timetable','/timetable','fa-clock']]},
  {title:'Boarding Configuration',description:'Configure and monitor boarders, rooms, houses, Exeat and incidents.',icon:'fa-building-shield',links:[['Boarding dashboard','/admin/boarding','fa-chart-pie'],['Boarding and rooms','/housemaster/boarding','fa-bed'],['Exeat reports','/admin/boarding','fa-person-walking-arrow-right'],['Incident reports','/admin/boarding','fa-triangle-exclamation']]},
  {title:'Communication & SMS',description:'Manage announcements and monitor Hubtel guardian SMS delivery.',icon:'fa-message',links:[['Announcements','/announcements','fa-bullhorn'],['Failed SMS reports','/announcements','fa-circle-exclamation'],['Missing guardian contacts','/admin/boarding','fa-address-book']]},
  {title:'Finance & Reporting',description:'Open billing records and the consolidated reporting centre.',icon:'fa-file-invoice-dollar',links:[['Billing','/fees','fa-wallet'],['Reports centre','/reports','fa-file-lines'],['Attendance reports','/attendance-reports','fa-calendar-check'],['Assessment reports','/assessment-reports','fa-chart-column']]},
];

export default async function SettingsPage(){
  const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)redirect('/login');
  const {data:profile}=await supabase.from('users').select('school_id,role,is_active').eq('id',user.id).maybeSingle(); if(!profile||profile.role!=='admin'||profile.is_active===false||!profile.school_id)redirect('/login');
  const [{data:years},{data:terms},{count:accounts},{count:staff}]=await Promise.all([
    supabase.from('academic_years').select('id,name,is_current,start_date').eq('school_id',profile.school_id).order('start_date',{ascending:false}),
    supabase.from('terms').select('id,name,is_current,academic_year_id').order('start_date',{ascending:true}),
    supabase.from('users').select('*',{count:'exact',head:true}).eq('school_id',profile.school_id).eq('is_active',true),
    supabase.from('staff').select('*',{count:'exact',head:true}).eq('school_id',profile.school_id).eq('status','active'),
  ]);
  const currentYear=years?.find(y=>y.is_current)||years?.[0]; const currentTerm=terms?.find(t=>t.is_current)||(currentYear?terms?.find(t=>t.academic_year_id===currentYear.id):undefined);
  return <main className="min-h-screen bg-slate-50 px-4 pb-12 pt-20 sm:px-6 lg:px-10 lg:pt-10"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"/><div className="mx-auto max-w-7xl space-y-6">
    <header className="rounded-3xl bg-gradient-to-br from-slate-950 via-slate-900 to-indigo-950 p-7 text-white shadow-xl"><p className="text-xs font-black uppercase tracking-[.2em] text-indigo-300">System Administration</p><h1 className="mt-2 text-3xl font-black"><i className="fa-solid fa-gears mr-3 text-cyan-300"/>Settings</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-300">Configure the school’s academic structure, users, boarding operations, communication and reporting tools.</p></header>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Academic year',currentYear?.name||'Not set','fa-calendar-days'],['Current semester',currentTerm?.name||'Not set','fa-calendar-week'],['Active accounts',String(accounts||0),'fa-user-shield'],['Active staff',String(staff||0),'fa-users']].map(([label,value,icon])=><div key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><i className={`fa-solid ${icon} text-indigo-600`}/><p className="mt-3 text-xs font-black uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-xl font-black text-slate-950">{value}</p></div>)}</section>
    <section className="grid gap-5 lg:grid-cols-2">{groups.map(group=><article key={group.title} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex gap-4"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-indigo-50 text-indigo-600"><i className={`fa-solid ${group.icon}`}/></span><div><h2 className="text-xl font-black text-slate-950">{group.title}</h2><p className="mt-1 text-sm leading-6 text-slate-500">{group.description}</p></div></div><div className="mt-5 grid gap-2 sm:grid-cols-2">{group.links.map(([label,href,icon])=><Link key={`${label}-${href}`} href={href} className="group flex items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm font-bold text-slate-700 transition hover:border-indigo-300 hover:bg-indigo-50 hover:text-indigo-700"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-white shadow-sm"><i className={`fa-solid ${icon}`}/></span><span className="flex-1">{label}</span><i className="fa-solid fa-chevron-right text-[10px] text-slate-300 group-hover:text-indigo-600"/></Link>)}</div></article>)}</section>
    <section className="rounded-3xl border border-amber-200 bg-amber-50 p-6"><h2 className="font-black text-amber-900"><i className="fa-solid fa-shield-halved mr-2"/>Protected configuration</h2><p className="mt-2 text-sm leading-6 text-amber-800">Hubtel credentials and secret system keys remain protected in Vercel Environment Variables and are never displayed in the browser. SMS results and failures can be monitored from Announcements and Boarding reports.</p></section>
  </div></main>;
}
