'use client';
import {useEffect,useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import {createClient} from '@/lib/supabase/client';
const supabase=createClient();
type P={id:string;school_id:string;full_name:string;role:string;is_active:boolean|null};
type Y={id:string;name:string;start_date:string;is_current:boolean|null}; type T={id:string;academic_year_id:string;name:string;is_current:boolean|null};
type H={id:string;name:string;gender:string|null;is_active:boolean}; type R={id:string;house_id:string;room_number:string;location:string|null;capacity:number;is_active:boolean};
type S={id:string;full_name:string;admission_number:string|null}; type C={id:string;name:string;level:string|null;programme_id:string|null;academic_year_id:string};
type G={id:string;name:string;code:string|null}; type E={student_id:string;class_id:string;academic_year_id:string;programme_id:string|null;status:string};
type A={id:string;student_id:string;academic_year_id:string;term_id:string|null;term:string|null;house_id:string;room_id:string;bed_space:string|null;status:string;allocated_at:string};
const input='h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm font-semibold outline-none focus:ring-4 focus:ring-slate-100';

export default function BoardingRegister(){
 const router=useRouter(); const [p,setP]=useState<P|null>(null),[loading,setLoading]=useState(true);
 const [years,setYears]=useState<Y[]>([]),[terms,setTerms]=useState<T[]>([]),[houses,setHouses]=useState<H[]>([]),[rooms,setRooms]=useState<R[]>([]),[students,setStudents]=useState<S[]>([]),[classes,setClasses]=useState<C[]>([]),[programmes,setProgrammes]=useState<G[]>([]),[enrol,setEnrol]=useState<E[]>([]),[alloc,setAlloc]=useState<A[]>([]);
 const [year,setYear]=useState(''),[term,setTerm]=useState(''),[termText,setTermText]=useState('Semester 1'),[search,setSearch]=useState('');
 const [move,setMove]=useState<A|null>(null),[moveHouse,setMoveHouse]=useState(''),[moveRoom,setMoveRoom]=useState(''),[moveBed,setMoveBed]=useState(''),[moving,setMoving]=useState(false),[notice,setNotice]=useState('');
 async function load(school:string){const q=await Promise.all([
  supabase.from('academic_years').select('id,name,start_date,is_current').eq('school_id',school).order('start_date',{ascending:false}),
  supabase.from('terms').select('id,academic_year_id,name,is_current'),
  supabase.from('residential_houses').select('id,name,gender,is_active').eq('school_id',school).eq('is_active',true).order('name'),
  supabase.from('residential_rooms').select('id,house_id,room_number,location,capacity,is_active').eq('school_id',school).eq('is_active',true).order('room_number'),
  supabase.from('students').select('id,full_name,admission_number').eq('school_id',school).eq('resident','Boarding').eq('status','active').order('full_name'),
  supabase.from('classes').select('id,name,level,programme_id,academic_year_id').eq('school_id',school),
  supabase.from('programmes').select('id,name,code').eq('school_id',school),
  supabase.from('enrollments').select('student_id,class_id,academic_year_id,programme_id,status').eq('status','active'),
  supabase.from('boarding_allocations').select('id,student_id,academic_year_id,term_id,term,house_id,room_id,bed_space,status,allocated_at').eq('school_id',school).eq('status','Active')
 ]);const er=q.find(x=>x.error)?.error;if(er)throw er;
 setYears((q[0].data||[])as Y[]);setTerms((q[1].data||[])as T[]);setHouses((q[2].data||[])as H[]);setRooms((q[3].data||[])as R[]);setStudents((q[4].data||[])as S[]);setClasses((q[5].data||[])as C[]);setProgrammes((q[6].data||[])as G[]);setEnrol((q[7].data||[])as E[]);setAlloc((q[8].data||[])as A[]);
 const cy=(q[0].data||[]).find((x:any)=>x.is_current)||(q[0].data||[])[0];if(cy&&!year)setYear(cy.id)}
 useEffect(()=>{(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return}const{data:u}=await supabase.from('users').select('id,school_id,full_name,role,is_active').eq('id',user.id).maybeSingle();if(!u||u.is_active===false||!['housemaster','admin'].includes(u.role)){router.replace('/login');return}setP(u as P);try{await load(u.school_id)}finally{setLoading(false)}})()},[router]);
 const yt=useMemo(()=>terms.filter(t=>t.academic_year_id===year),[terms,year]);useEffect(()=>{const x=yt.find(t=>t.is_current)||yt[0];setTerm(x?.id||'');if(x)setTermText(x.name)},[year,yt.length]);
 const scoped=alloc.filter(a=>a.academic_year_id===year&&(term?a.term_id===term:!a.term_id));const allocated=new Set(scoped.map(a=>a.student_id));const needs=students.filter(s=>!allocated.has(s.id));const capacity=rooms.reduce((n,r)=>n+r.capacity,0);
 function meta(id:string){const s=students.find(x=>x.id===id);const e=enrol.find(x=>x.student_id===id&&x.academic_year_id===year)||enrol.find(x=>x.student_id===id);const c=e?classes.find(x=>x.id===e.class_id):undefined;const g=programmes.find(x=>x.id===(e?.programme_id||c?.programme_id));return{s,c,g}}
 const matches=(id:string)=>{const x=meta(id);return `${x.s?.full_name||''} ${x.s?.admission_number||''} ${x.g?.name||''} ${x.g?.code||''}`.toLowerCase().includes(search.toLowerCase())};
 async function transfer(){if(!move||!p||!moveHouse||!moveRoom||!moveBed.trim())return;setMoving(true);setNotice('');const {error}=await supabase.rpc('transfer_boarding_student',{p_student_id:move.student_id,p_academic_year_id:year,p_term_id:term||null,p_term:termText,p_house_id:moveHouse,p_room_id:moveRoom,p_bed_space:moveBed.trim(),p_notes:'Room/bed transfer'});if(error){setNotice(error.message)}else{setNotice('Transfer completed. Previous allocation preserved as Transferred.');setMove(null);setMoveHouse('');setMoveRoom('');setMoveBed('');await load(p.school_id)}setMoving(false)}
 if(loading)return <main className="min-h-screen bg-slate-50 p-6"><div className="h-40 animate-pulse rounded-3xl bg-slate-900"/></main>;
 return <main className="min-h-screen bg-slate-50 px-4 py-5 sm:px-6 lg:px-8"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"/><div className="mx-auto max-w-7xl space-y-6">
 <header className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-slate-950 via-slate-900 to-slate-800 p-6 text-white shadow-xl sm:p-8"><div className="absolute -right-16 -top-16 h-44 w-44 animate-pulse rounded-full bg-white/5"/><div className="relative"><span className="inline-flex rounded-full bg-white/10 px-3 py-1.5 text-xs font-black"><i className="fa-solid fa-bed mr-2 animate-pulse"/>Boarders Only</span><h1 className="mt-4 text-2xl font-black sm:text-3xl">Boarding Houses & Room Register</h1><p className="mt-2 text-sm text-slate-300">Students are grouped by House and Room for the selected academic period. Previous allocations remain in history when students move.</p></div></header>
 <section className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[['Boarders',students.length,'fa-users'],['Allocated',scoped.length,'fa-bed'],['Needs Allocation',needs.length,'fa-user-clock'],['Available Beds',Math.max(0,capacity-scoped.length),'fa-door-open']].map(([l,v,i])=><div key={String(l)} className="group rounded-2xl border bg-white p-4 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-100 transition-transform group-hover:scale-110"><i className={`fa-solid ${i}`}/></span><p className="mt-3 text-2xl font-black">{v}</p><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">{l}</p></div>)}</section>
 <section className="rounded-3xl border bg-white p-5 shadow-sm"><div className="grid gap-4 md:grid-cols-3"><label><span className="mb-1 block text-xs font-bold">Academic Year</span><select className={input} value={year} onChange={e=>setYear(e.target.value)}>{years.map(y=><option key={y.id} value={y.id}>{y.name}</option>)}</select></label><label><span className="mb-1 block text-xs font-bold">Semester</span>{yt.length?<select className={input} value={term} onChange={e=>{setTerm(e.target.value);setTermText(yt.find(t=>t.id===e.target.value)?.name||'')}}>{yt.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select>:<select className={input} value={termText} onChange={e=>setTermText(e.target.value)}><option>Semester 1</option><option>Semester 2</option></select>}</label><label><span className="mb-1 block text-xs font-bold">Search</span><input className={input} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name, admission no., programme"/></label></div></section>
 <section className="rounded-3xl border border-amber-200 bg-amber-50/50 p-5"><div className="flex items-center justify-between"><div><h2 className="font-black text-slate-900"><i className="fa-solid fa-user-clock mr-2 text-amber-600"/>Needs Room Allocation</h2><p className="mt-1 text-xs text-slate-500">Includes promoted/returning Boarders without a room for this period.</p></div><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-black text-amber-800">{needs.length}</span></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{needs.filter(s=>matches(s.id)).slice(0,120).map(s=>{const x=meta(s.id);return <div key={s.id} className="rounded-xl bg-white p-3 shadow-sm"><p className="text-sm font-black">{s.full_name}</p><p className="mt-1 text-xs text-slate-500">{s.admission_number||'No admission no.'} · {x.g?.code||x.g?.name||'No programme'} · {x.c?.level||'No form'}</p></div>})}</div></section>
 {houses.map((h,hi)=><section key={h.id} className="overflow-hidden rounded-3xl border bg-white shadow-sm animate-[fadeInUp_.45s_ease-out_both]" style={{animationDelay:`${hi*60}ms`}}><div className="border-b bg-slate-50 p-5"><h2 className="text-lg font-black"><i className="fa-solid fa-building mr-2 text-slate-400"/>{h.name}</h2><p className="text-xs text-slate-500">{h.gender||'Mixed'} House</p></div><div className="grid gap-4 p-5 lg:grid-cols-2">{rooms.filter(r=>r.house_id===h.id).map(r=>{const ra=scoped.filter(a=>a.room_id===r.id);return <div key={r.id} className="overflow-hidden rounded-2xl border"><div className="flex items-center justify-between border-b p-4"><div><h3 className="font-black">{r.room_number}</h3><p className="text-xs text-slate-500">{r.location||'Location not specified'}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-black ${ra.length>=r.capacity?'bg-red-50 text-red-700':'bg-emerald-50 text-emerald-700'}`}>{ra.length}/{r.capacity}</span></div><div className="divide-y">{ra.filter(a=>matches(a.student_id)).length?ra.filter(a=>matches(a.student_id)).map(a=>{const x=meta(a.student_id);return <div key={a.id} className="group flex items-center gap-3 p-3 transition hover:bg-slate-50"><span className="flex min-h-10 min-w-10 items-center justify-center rounded-xl bg-slate-900 px-2 text-[10px] font-black text-white transition-transform group-hover:scale-105">{a.bed_space||'—'}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-black">{x.s?.full_name||'Student'}</p><p className="truncate text-xs text-slate-500">{x.s?.admission_number||'No admission no.'} · {x.g?.code||x.g?.name||'No programme'} · {x.c?.level||'—'} · {a.bed_space||'No bed'}</p></div><button type="button" onClick={()=>{setMove(a);setMoveHouse(a.house_id);setMoveRoom(a.room_id);setMoveBed('');setNotice('')}} className="rounded-lg bg-slate-100 px-2.5 py-2 text-[10px] font-black text-slate-600 transition hover:-translate-y-0.5 hover:bg-slate-900 hover:text-white"><i className="fa-solid fa-right-left mr-1"/>Move</button></div>}):<p className="p-5 text-center text-xs text-slate-400">No matching students in this room.</p>}</div></div>})}</div></section>)}
 {move&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/60 p-4 backdrop-blur-sm"><div className="w-full max-w-lg animate-[fadeInUp_.25s_ease-out] rounded-3xl bg-white p-5 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-black uppercase tracking-widest text-indigo-600">Safe Transfer</p><h3 className="mt-1 text-xl font-black">Move Boarder</h3><p className="mt-1 text-xs text-slate-500">The current allocation will be preserved as Transferred.</p></div><button type="button" onClick={()=>setMove(null)} className="flex h-9 w-9 items-center justify-center rounded-xl bg-slate-100"><i className="fa-solid fa-xmark"/></button></div><div className="mt-5 grid gap-4"><label><span className="mb-1 block text-xs font-bold">New House</span><select className={input} value={moveHouse} onChange={e=>{setMoveHouse(e.target.value);setMoveRoom('');setMoveBed('')}}>{houses.map(h=><option key={h.id} value={h.id}>{h.name}</option>)}</select></label><label><span className="mb-1 block text-xs font-bold">New Room</span><select className={input} value={moveRoom} onChange={e=>{setMoveRoom(e.target.value);setMoveBed('')}}><option value="">Select room</option>{rooms.filter(r=>r.house_id===moveHouse).map(r=>{const n=scoped.filter(a=>a.room_id===r.id&&a.id!==move.id).length;return <option key={r.id} value={r.id} disabled={n>=r.capacity}>{r.room_number} — {n}/{r.capacity} occupied</option>})}</select></label><label><span className="mb-1 block text-xs font-bold">New Bed Number</span><input className={input} value={moveBed} onChange={e=>setMoveBed(e.target.value)} placeholder="e.g. Bed 3"/></label>{notice&&<p className="rounded-xl bg-red-50 p-3 text-xs font-bold text-red-700">{notice}</p>}<button type="button" disabled={moving||!moveRoom||!moveBed.trim()} onClick={transfer} className="h-11 rounded-xl bg-slate-900 text-sm font-black text-white transition hover:-translate-y-0.5 disabled:opacity-50"><i className={`fa-solid ${moving?'fa-spinner animate-spin':'fa-right-left'} mr-2`}/>{moving?'Transferring...':'Confirm Transfer'}</button></div></div></div>}
 </div></main>
}
